name: "Mohak Gangwani"
designations: "Data Scientist, Machine Learning Engineer, Analytics Consultant, Freelancer"
index:
  introduction: "Welcome! I am Mohak Gangwani, a Data Science professional with a strong foundation in mathematics and a passion for solving complex problems through data. With expertise in machine learning, NLP, forecasting, and data visualization, I specialize in developing innovative solutions that drive impactful insights. Having recently completed my M.S. in Data Science, I am excited to apply my skills and knowledge to create meaningful outcomes. Explore my portfolio to learn more about my journey, skills, and projects."

resume:
  Education:
    - degree: "M.S. Data Science, University of Nottingham"
      time_period: "Sep 2023 – Sep 2024"
      details:
        - "Relevant Modules: Machine Learning, Applied Statistics, Big Data, etc."
    - degree: "B.Sc. Mathematics (Hons), University of Delhi"
      time_period: "Jul 2017 – Aug 2020"
      details:
        - "GPA: 3.33/4.00 | Modules: Linear Algebra, Calculus, Statistics"
  Work Experience:
    - position: "Associate Project Lead - Data Science"
      company: "Escalent"
      time_period: "Jan 2023 – Aug 2023"
      details:
        - "Independently managed multiple projects while also providing guidance and mentorship to junior team members."
        - "Designed Natural Language Processing (NLP) frameworks using Python allowing the user to create multiple use cases like Sentiment Analysis & Topic Modelling along with features like Model Evaluation and Hyperparameter Tuning."
        - "Designed and launched a forecasting application using Python (Django), incorporating Sensitivity and What-if Analysis to analyze 200+ cost variables for an educational organization."
        - "Developed and deployed customer segmentation models and A/B testing to optimize marketing strategies, improving targeting with data-driven insights."
        - "Created an Analytical Tool using Python & Excel to project a brand's market share, allowing the client to analyse how different parameters affect the projected value, with an accuracy of 85%+."
    - position: "Analyst - Data Science"
      company: "Escalent"
      time_period: "Jan 2022 – Dec 2022"
      details:
        - "Developed a 12-month rolling time-series model using R to forecast the Share of Market (SOM) of a brand."
        - "Deployed scalable, automated machine learning pipelines utilizing modern MLOps practices, resulting in a 30% reduction in model training time."
        - "Derived a forecast model using Python to project the SOM of a product category in different states maintaining a minimum accuracy of 75% while dealing with noisy data."
        - "Built and deployed customer segmentation and churn analysis models using Python, combining lifecycle modelling with Marketing Mix Modelling to enhance customer engagement."
        - "Conducted knowledge transfer sessions to facilitate the smooth onboarding of new team members."
    - position: "Management Trainee - Data Science"
      company: "Escalent"
      time_period: "Jan 2022 – Dec 2022"
      details:
        - "Formalized an automated tool using Python (Selenium, BeautifulSoup) to extract data, improving accuracy and efficiency by more than 300%."
        - "Automated the forecast model-building process using Python, improving efficiency and productivity by more than 100%."
        - "Designed PowerBI dashboards to visualize actionable KPIs, improving client management and resource allocation."
        - "Proposed and implemented a tool to track the impact of taxes on the company’s sales and revenue, helping the company plan ahead of time."
        - "Formalized an automated tool to generate reports of daily/monthly/quarterly sales of 5+ product categories using Python (Pandas, Numpy)."
    
  Skills:
    - category: "Programming Languages"
      list: 
        - "Python"
        - "R"
        - "OOPS (Object Oriented Programming)"
        - "Data Science Libraries"
    - category: "Data Science Techniques"
      list: 
        - "Machine Learning"
        - "Deep Learning"
        - "Natural Language Processing (NLP)"
        - "Time Series FOrecasting"
        - "Customer Segmentation"
        - "Market Mix Modelling"
        - "A/B Testing"
        - "Optimization"
        - "Big Data Techniques"
    - category: "Databases"
      list: 
        - "SQL"
        - "NoSQL"
    - category: "Deployment & CLoud Tools"
      list: 
        - "Git"
        - "GitHub"
        - "DagsHub"
        - "MLFlow"
        - "Data Version Control (DVC)"
        - "Docker"
        - "AWS"
    - category: "Data Visualization & Dashboarding"
      list: 
        - "PowerBI"
        - "Tableau"
        - "Advanced Excel"
    - category: "Other Tools & Softwares"
      list: 
      - "Linux & Command Line Commands"
  Recommendations:
    - name: "Sameer Saurabh"
      designation: "Director - Data Science"
      company: "Escalent"
      details:
        - "Recommendation here"
    - name: "Lokesh Vaishnav"
      designation: "Analyst - Data Science"
      company: "Escalent"
      details:
        - "Recommendation here"

projects:
  - title: "Movie Recommender System"
    description: "A Python-based framework for sentiment analysis and topic modeling."
  - title: "Image Captioning"
    description: "Built a Django app for sensitivity analysis of 200+ cost variables."